#include"NEEDED.H"

void Interface(void)
{
	clrscr();
	printf("********************************************************************************\n");
	printf("***  [1]News    ***    [2]Notice    ***    [3]Account-Management    [0]Exit  ***\n");
	printf("********************************************************************************\n");
}


/*
***********************************************
*         Designed by Dylan Simon Su          *
*  Translation comes from Baidu translation.  *
*          Dylan Simon Su copyright.          *
***********************************************
*/
