#include"NEEDED.H"

int main()
{
	int key = 9, idkey = 0;
	while(key == 9)
	{
		IndentityMenu(&key);
		getchar();
	}
	switch(key)
	{
		case 1:
			idkey = UserNode* Login( !?! );//!?! -> Chained File
			Interface();
			break;
		case 2:
			Interface();
			!?! = NULL;//!?! -> Chained File
			break;
		case 3:
			break;
		case 0:
			return 0;
	}

	printf("  Thinks for using!\n");
	return 0;
}
